/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment.humanquiz;
import  javax.swing.*;

/**
 *
 * @author Tarun
 */
public class BiologyQuiz extends javax.swing.JFrame {

    /**
     * Creates new form BiologyQuiz
     */
    public BiologyQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        Question1 = new javax.swing.JLabel();
        Question2 = new javax.swing.JLabel();
        Question4 = new javax.swing.JLabel();
        Question3 = new javax.swing.JLabel();
        Question5 = new javax.swing.JLabel();
        Question1TextBox = new javax.swing.JTextField();
        Question4TextBox = new javax.swing.JTextField();
        Question3TextBox = new javax.swing.JTextField();
        Question2TextBox = new javax.swing.JTextField();
        Question5TextBox = new javax.swing.JTextField();
        FinalScoreLabel = new javax.swing.JLabel();
        YourScoreLabel = new javax.swing.JLabel();
        Statement = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TitleLabel.setText("BIOLOGY QUIZ!");

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        Question1.setText("1.  Whats the biggest organ in your body?");

        Question2.setText("2. The bones that make up  your spine are called____");

        Question4.setText("4.What does the innermost of the bone contain?");

        Question3.setText("3.Another name for your voice box is_____");

        Question5.setText("5. When do babies start to shed tears?");

        Question1TextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question1TextBoxActionPerformed(evt);
            }
        });

        Question4TextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question4TextBoxActionPerformed(evt);
            }
        });

        Question3TextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question3TextBoxActionPerformed(evt);
            }
        });

        Question2TextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question2TextBoxActionPerformed(evt);
            }
        });

        Question5TextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question5TextBoxActionPerformed(evt);
            }
        });

        FinalScoreLabel.setBackground(new java.awt.Color(255, 255, 255));

        YourScoreLabel.setText("Your Score  : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(YourScoreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FinalScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Statement, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Question1TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Question1)
                            .addComponent(Question2)
                            .addComponent(Question2TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Question3)
                            .addComponent(Question3TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Question4)
                            .addComponent(Question4TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Question5)
                            .addComponent(Question5TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Question1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Question1TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Question2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Question2TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Question3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Question3TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Question4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Question4TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Question5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question5TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FinalScoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addComponent(SubmitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(YourScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Statement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Question5TextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question5TextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question5TextBoxActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed

        int marks = 0;
        
        
        if (("SKIN".equals(Question1TextBox.getText().toUpperCase()))) {
            marks++;
        }

        if (("VERTEBRAE".equals(Question2TextBox.getText().toUpperCase()))) {
            marks++;
        }

        if (("LARYNX".equals(Question3TextBox.getText().toUpperCase())))  {
            marks++;
        }

        if (("BONE MARROW".equals(Question4TextBox.getText().toUpperCase())))  {
            marks++;
        }
        else if (("BONEMARROW".equals(Question4TextBox.getText().toUpperCase()))) {
            marks++;
        }

        if (("1 MONTH".equals(Question5TextBox.getText().toUpperCase()))){
            marks++;
        }
        else if (("ONE MONTH".equals(Question5TextBox.getText().toUpperCase())))  {
            marks++;
        }
        else if (("1".equals(Question5TextBox.getText().toUpperCase())))  {
            marks++;
        }
        FinalScoreLabel.setText((marks + "/ 5"));
        switch (marks) {
            case 0:
           Statement.setText(( "oof you failed"));
            break;
            case 1:
            Statement.setText ("you got a 1, you need to start trying");
            break;
            case 2:
            Statement.setText ( "you have a 2, you could do better");
            break;
            case 3:
            Statement.setText ( "you passed!");
            break;
            case 4:
            Statement.setText ( "Almost there");
            break;
            case 5:
           Statement.setText ("You aced it!");
            break;
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void Question1TextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question1TextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question1TextBoxActionPerformed

    private void Question4TextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question4TextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question4TextBoxActionPerformed

    private void Question3TextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question3TextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question3TextBoxActionPerformed

    private void Question2TextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question2TextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Question2TextBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiologyQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiologyQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiologyQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiologyQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiologyQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FinalScoreLabel;
    private javax.swing.JLabel Question1;
    private javax.swing.JTextField Question1TextBox;
    private javax.swing.JLabel Question2;
    private javax.swing.JTextField Question2TextBox;
    private javax.swing.JLabel Question3;
    private javax.swing.JTextField Question3TextBox;
    private javax.swing.JLabel Question4;
    private javax.swing.JTextField Question4TextBox;
    private javax.swing.JLabel Question5;
    private javax.swing.JTextField Question5TextBox;
    private javax.swing.JLabel Statement;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel YourScoreLabel;
    // End of variables declaration//GEN-END:variables
}
